services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
            - ./docker/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
        expose:
            - "9000"
            - "9003"
        depends_on:
            - db
        environment:
            APP_ENV: local
            APP_DEBUG: true
            DB_CONNECTION: mysql
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: game_catalog
            DB_USERNAME: root
            DB_PASSWORD: root
            XDEBUG_MODE: debug
            XDEBUG_CONFIG: "client_host=host.docker.internal log_level=0"
            XDEBUG_SESSION: PHPSTORM
        extra_hosts:
            - "host.docker.internal:host-gateway"
        networks:
            - laravel_network

    nginx:
        image: nginx:alpine
        container_name: laravel_nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel_network

    db:
        image: mysql:8
        container_name: laravel_db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: game_catalog
            MYSQL_ROOT_PASSWORD: root
            MYSQL_TCP_PORT: 3306
        ports:
            - "3307:3306"
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel_network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: laravel_phpmyadmin
        restart: unless-stopped
        depends_on:
            - db
        ports:
            - "8080:80"
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: root
        networks:
            - laravel_network

volumes:
    dbdata:

networks:
    laravel_network:
        driver: bridge
